spring:
  application:
    name: izone-service
  datasource:
    url: jdbc:mysql://10.10.10.9:3306/izone
    username: root
    password: izone@20244202
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline-version: 5
  jpa:
    show-sql: true